#!/usr/bin/env python3
"""Dev bot main loop — Python Agent SDK version."""

import argparse
import asyncio
import json
import logging
import os
import shutil
import signal
import subprocess
import sys
import time
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen

from dotenv import load_dotenv
from filelock import FileLock, Timeout

from .agent import run_cycle
from .config import (
    ALLOWED_TOOLS,
    Config,
    InstanceConfig,
    load_config,
    load_instance_config,
    load_mcp_servers,
    resolve_workflow_dir,
    sanitize_env,
    validate_instance_config,
    validate_manifest,
)
from .costs import record_cost
from .merge import apply_merged_config
from .preflight import run_preflight
from .transcripts import post_orphan_cycle, record_transcript

SCRIPT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = SCRIPT_DIR / "data"


def _resolve_path(p: str) -> str:
    """Resolve a path that may be relative to SCRIPT_DIR, ~, or absolute."""
    path = Path(p).expanduser()
    if not path.is_absolute():
        path = SCRIPT_DIR / path
    return str(path.resolve())


def setup_git(script_dir: Path) -> None:
    """Generate per-platform .gitconfig files with includeIf.

    Reads GH_USER_NAME/GH_USER_EMAIL and GL_USER_NAME/GL_USER_EMAIL
    from env. Each platform gets its own identity and signing key.
    Sets GIT_CONFIG_GLOBAL so all repos use this config.
    """
    gh_name = os.environ.get("GH_USER_NAME")
    gh_email = os.environ.get("GH_USER_EMAIL")
    gl_name = os.environ.get("GL_USER_NAME")
    gl_email = os.environ.get("GL_USER_EMAIL")

    if not gh_name and not gl_name:
        return

    config_path = script_dir / ".gitconfig"
    gh_config = script_dir / ".gitconfig-gh"
    gl_config = script_dir / ".gitconfig-gl"

    for path, name, email, key_env in [
        (gh_config, gh_name, gh_email, "GH_GPG_SIGNING_KEY"),
        (gl_config, gl_name, gl_email, "GL_GPG_SIGNING_KEY"),
    ]:
        lines = ["# Auto-generated by bot/run.py", "[user]"]
        if name:
            lines.append(f"\tname = {name}")
        if email:
            lines.append(f"\temail = {email}")
        signing_key = os.environ.get(key_env) or os.environ.get("GPG_SIGNING_KEY")
        if signing_key:
            lines.append(f"\tsigningkey = {signing_key}")
        path.write_text("\n".join(lines) + "\n")

    lines = [
        "# Auto-generated by bot/run.py — do not edit manually",
        '[includeIf "hasconfig:remote.*.url:https://github.com/**"]',
        f"\tpath = {gh_config}",
        '[includeIf "hasconfig:remote.*.url:https://gitlab.cee.redhat.com/**"]',
        f"\tpath = {gl_config}",
        "[commit]",
        "\tgpgsign = true",
        "[gpg]",
        "\tformat = openpgp",
        '[credential "https://github.com"]',
        "\thelper = !/usr/local/bin/gh auth git-credential",
        '[credential "https://gitlab.cee.redhat.com"]',
        "\thelper = !/usr/local/bin/glab credential-helper",
    ]

    config_path.write_text("\n".join(lines) + "\n")
    os.environ["GIT_CONFIG_GLOBAL"] = str(config_path)


def setup_logging() -> None:
    """Configure logging to stdout and data/bot.log."""
    DATA_DIR.mkdir(exist_ok=True)
    fmt = "[%(asctime)s] %(message)s"
    datefmt = "%Y-%m-%d %H:%M:%S"

    handlers: list[logging.Handler] = [
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(DATA_DIR / "bot.log", mode="a"),
    ]

    logging.basicConfig(
        level=logging.INFO,
        format=fmt,
        datefmt=datefmt,
        handlers=handlers,
    )


REMOTE_CONFIG_DIR = DATA_DIR / "remote-config"


def sync_config_repo() -> Path | None:
    """Clone or pull BOT_CONFIG_REPO. Returns agent config dir or None."""
    logger = logging.getLogger(__name__)
    repo_url = os.environ.get("BOT_CONFIG_REPO")
    if not repo_url:
        return None

    config_dir = REMOTE_CONFIG_DIR
    try:
        if (config_dir / ".git").exists():
            r = subprocess.run(
                ["git", "-C", str(config_dir), "pull", "--ff-only"],
                capture_output=True,
                timeout=30,
                check=False,
            )
            if r.returncode != 0:
                logger.warning(
                    "git pull failed (rc=%d): %s",
                    r.returncode,
                    r.stderr.decode().strip(),
                )
        else:
            config_dir.parent.mkdir(parents=True, exist_ok=True)
            r = subprocess.run(
                ["git", "clone", "--depth", "1", repo_url, str(config_dir)],
                capture_output=True,
                timeout=60,
                check=False,
            )
            if r.returncode != 0:
                logger.warning(
                    "git clone failed (rc=%d): %s",
                    r.returncode,
                    r.stderr.decode().strip(),
                )
                return None
    except subprocess.TimeoutExpired:
        logger.warning("Config repo sync timed out — using built-in config")
        return None
    except Exception as exc:
        logger.warning("Config repo sync failed: %s — using built-in config", exc)
        return None

    sub = os.environ.get("BOT_CONFIG_PATH", "rehor-config")
    agent_dir = config_dir / sub / "agent"
    if not agent_dir.is_dir():
        logger.warning("Config repo has no %s/agent/ dir — using built-in config", sub)
        return None

    return agent_dir


SLEEP_SIGNAL_FILE = DATA_DIR / "cycle-sleep.json"
LOW_DISK_THRESHOLD_MB = 512
WAKE_POLL_INTERVAL = 5

DASHBOARD_BASE_URL = os.environ.get("BOT_DASHBOARD_URL", "http://localhost:8080/api/bot-status").rsplit(
    "/bot-status", 1
)[0]


def _check_wake_signal(instance_id: str) -> bool:
    """Poll the memory server for a wake trigger. Returns True if wake requested."""
    try:
        url = f"{DASHBOARD_BASE_URL}/instances/{instance_id}/wake"
        with urlopen(url, timeout=2) as resp:
            data = json.loads(resp.read())
            return data.get("wake", False)
    except (URLError, OSError, json.JSONDecodeError, Exception):
        return False


def _write_sleep_signal(seconds: int, reason: str) -> None:
    """Write a sleep signal file for the runner to read after the cycle."""
    SLEEP_SIGNAL_FILE.parent.mkdir(parents=True, exist_ok=True)
    SLEEP_SIGNAL_FILE.write_text(json.dumps({"recommended_sleep": seconds, "reason": reason}))


def _read_sleep_signal(config: Config, instance_id: str | None = None) -> int:
    """Read sleep duration from skill-written signal file.

    Skills write data/cycle-sleep.json with {"recommended_sleep": N, "reason": "..."}.
    No file = standard interval (work was done). File is always deleted after reading.

    Instead of blocking for the full duration, sleeps in short intervals and polls
    the memory server for a wake trigger so the dashboard can interrupt the sleep.
    """
    logger = logging.getLogger(__name__)
    sleep_seconds = config.interval

    if SLEEP_SIGNAL_FILE.exists():
        try:
            sig = json.loads(SLEEP_SIGNAL_FILE.read_text())
            sleep_seconds = sig.get("recommended_sleep", config.interval)
            reason = sig.get("reason", "")
            logger.info("Sleep signal: %ds (%s)", sleep_seconds, reason)
        except Exception:
            logger.warning("Bad sleep signal file, using default %ds", config.interval)
        finally:
            SLEEP_SIGNAL_FILE.unlink(missing_ok=True)
    else:
        logger.info("No sleep signal, using default %ds", config.interval)

    sleep_seconds = max(sleep_seconds, WAKE_POLL_INTERVAL)
    logger.info("Sleeping for %ds...", sleep_seconds)

    if instance_id:
        elapsed = 0
        while elapsed < sleep_seconds:
            time.sleep(WAKE_POLL_INTERVAL)
            elapsed += WAKE_POLL_INTERVAL
            if _check_wake_signal(instance_id):
                logger.info(
                    "Wake signal received after %ds — starting next cycle early",
                    elapsed,
                )
                return elapsed
    else:
        time.sleep(sleep_seconds)

    return sleep_seconds


def assemble_claude_md(
    script_dir: Path,
    instance_config: InstanceConfig | None = None,
    remote_agent_dir: Path | None = None,
) -> None:
    """Concatenate core + workflow preset CLAUDE.md into project root.

    Supports instance CLAUDE.md via claude_md_strategy:
      replace — core + instance CLAUDE.md (skip workflow)
      append  — core + workflow + instance CLAUDE.md
      ignore  — core + workflow only (default)
    """
    logger = logging.getLogger(__name__)
    presets = script_dir / "presets"
    core = presets / "core" / "CLAUDE.md"

    workflow = instance_config.workflow if instance_config else os.environ.get("BOT_WORKFLOW_PRESET", "jira-sprint")
    strategy = instance_config.claude_md_strategy if instance_config else "ignore"

    if not core.is_file():
        logger.warning("Core CLAUDE.md not found at %s — skipping assembly", core)
        return

    parts = [core.read_text()]

    instance_md = remote_agent_dir / "CLAUDE.md" if remote_agent_dir else None
    has_instance_md = instance_md is not None and instance_md.is_file()

    if strategy == "replace" and has_instance_md:
        parts.append(instance_md.read_text())
        logger.info("CLAUDE.md strategy=replace — using instance CLAUDE.md instead of workflow")
    else:
        wf_path = resolve_workflow_dir(script_dir, workflow, remote_agent_dir) / "CLAUDE.md"
        if wf_path.is_file():
            parts.append(wf_path.read_text())
        else:
            logger.warning("Workflow CLAUDE.md not found at %s — using core only", wf_path)
        if strategy == "append" and has_instance_md:
            parts.append(instance_md.read_text())
            logger.info("CLAUDE.md strategy=append — appended instance CLAUDE.md")

    output = script_dir / "CLAUDE.md"
    output.write_text("".join(parts))
    logger.info("Assembled CLAUDE.md from core + %s (%d bytes)", workflow, output.stat().st_size)


def cleanup_between_cycles(script_dir: Path) -> None:
    """Free disk space between cycles if below threshold."""
    logger = logging.getLogger(__name__)

    SLEEP_SIGNAL_FILE.unlink(missing_ok=True)

    try:
        usage = shutil.disk_usage(str(script_dir))
        free_mb = usage.free // (1024 * 1024)
    except OSError:
        return

    if free_mb >= LOW_DISK_THRESHOLD_MB:
        logger.info("Disk OK: %dM free (threshold %dM)", free_mb, LOW_DISK_THRESHOLD_MB)
        return

    logger.warning(
        "Low disk: %dM free (threshold %dM) — cleaning up",
        free_mb,
        LOW_DISK_THRESHOLD_MB,
    )

    for name, cmd in [
        ("Go build cache", ["go", "clean", "-cache"]),
        ("Go mod cache", ["go", "clean", "-modcache"]),
        ("npm cache", ["npm", "cache", "clean", "--force"]),
    ]:
        try:
            subprocess.run(cmd, capture_output=True, timeout=30)
            logger.info("Cleaned %s", name)
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass

    repos_dir = script_dir / "repos"
    if repos_dir.exists():
        for repo in repos_dir.iterdir():
            if (repo / ".git").is_dir():
                try:
                    subprocess.run(
                        ["git", "gc", "--auto", "--quiet"],
                        cwd=str(repo),
                        capture_output=True,
                        timeout=60,
                    )
                except (subprocess.TimeoutExpired, FileNotFoundError):
                    pass

    try:
        usage = shutil.disk_usage(str(script_dir))
        free_mb = usage.free // (1024 * 1024)
        logger.info("Cleanup done. Free space: %dM", free_mb)
    except OSError:
        pass


def main() -> None:
    # Load .env before anything else so MCP servers get the credentials
    load_dotenv(SCRIPT_DIR / ".env")

    # Set up git identity from env vars (no-op if not configured)
    setup_git(SCRIPT_DIR)

    parser = argparse.ArgumentParser(description="Dev bot agent loop")
    parser.add_argument(
        "--label",
        required=True,
        help="Primary Jira label (e.g. hcc-ai-framework)",
    )
    parser.add_argument(
        "--instance-id",
        default=os.environ.get("BOT_INSTANCE_ID", ""),
        help="Bot instance ID for multi-instance isolation (default: $BOT_INSTANCE_ID)",
    )
    args = parser.parse_args()

    if not args.instance_id:
        parser.error("--instance-id is required (or set BOT_INSTANCE_ID env var)")

    setup_logging()
    logger = logging.getLogger(__name__)

    config = load_config(SCRIPT_DIR)
    mcp_servers = load_mcp_servers(SCRIPT_DIR)

    # Initial config sync + instance config load (before validation so
    # instance.yaml can override the workflow preset)
    initial_agent_dir = sync_config_repo()
    if initial_agent_dir:
        apply_merged_config(SCRIPT_DIR, initial_agent_dir)
    instance_config = load_instance_config(initial_agent_dir)

    validate_manifest(SCRIPT_DIR, instance_config.workflow, mcp_servers, initial_agent_dir)
    validate_instance_config(SCRIPT_DIR, instance_config, initial_agent_dir)

    # Remove secrets from env so Bash subprocesses can't leak them.
    # MCP servers already have resolved values. gh/glab use config files.
    sanitize_env()
    logger.info("Sanitized environment — secrets removed from env vars.")

    # Lock file — prevent concurrent runs
    lock = FileLock(DATA_DIR / ".lock", timeout=0)
    try:
        lock.acquire()
    except Timeout:
        logger.error("Another instance is running. Exiting.")
        sys.exit(1)

    def shutdown(sig, frame):
        logger.info("Shutting down.")
        lock.release()
        sys.exit(0)

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    instance_id = args.instance_id or None
    logger.info(
        "Dev bot started. Label: %s. Instance: %s. Provider: Vertex AI. Active interval: %ds. Idle interval: %ds.",
        args.label,
        instance_id or "(none)",
        config.interval,
        config.idle_interval,
    )

    consecutive_preflight_errors = 0

    try:
        while True:
            remote_agent_dir = sync_config_repo()
            if remote_agent_dir:
                apply_merged_config(SCRIPT_DIR, remote_agent_dir)

            instance_config = load_instance_config(remote_agent_dir)
            assemble_claude_md(SCRIPT_DIR, instance_config, remote_agent_dir)

            # --- Pre-flight: gather data before starting AI session ---
            preflight_result = run_preflight(SCRIPT_DIR, instance_config.workflow, remote_agent_dir, instance_id)

            preflight_prompt = None
            if preflight_result is not None:
                if preflight_result.action == "error":
                    consecutive_preflight_errors += 1
                    logger.error("Preflight error (consecutive: %d)", consecutive_preflight_errors)
                    post_orphan_cycle(instance_id or args.label, "error", preflight_result.transcript)
                    error_sleep = min(config.interval * (2**consecutive_preflight_errors), 300)
                    _write_sleep_signal(error_sleep, "preflight_error")
                    _read_sleep_signal(config, instance_id)
                    cleanup_between_cycles(SCRIPT_DIR)
                    continue

                if preflight_result.action == "skip":
                    consecutive_preflight_errors = 0
                    logger.info("Preflight skip — no session needed")
                    post_orphan_cycle(instance_id or args.label, "idle", preflight_result.transcript)
                    _write_sleep_signal(300, "preflight_skip")
                    _read_sleep_signal(config, instance_id)
                    cleanup_between_cycles(SCRIPT_DIR)
                    continue

                # action == "start"
                consecutive_preflight_errors = 0
                preflight_prompt = preflight_result.prompt
                logger.info("Preflight start — launching session with pre-fetched data")

            logger.info("Running agent cycle...")

            try:
                result, ctx = asyncio.run(
                    asyncio.wait_for(
                        run_cycle(
                            label=args.label,
                            config=config,
                            mcp_servers=mcp_servers,
                            allowed_tools=ALLOWED_TOOLS,
                            cwd=str(SCRIPT_DIR),
                            instance_id=instance_id,
                            preflight_prompt=preflight_prompt,
                        ),
                        timeout=config.cycle_timeout,
                    )
                )
            except asyncio.TimeoutError:
                logger.error(
                    "Cycle timed out after %ds — skipping to next cycle",
                    config.cycle_timeout,
                )
                result, ctx = None, None

            if result is not None:
                record_cost(
                    costs_file=DATA_DIR / "costs.jsonl",
                    label=args.label,
                    result=result,
                    ctx=ctx,
                )
                record_transcript(
                    label=args.label,
                    result=result,
                    ctx=ctx,
                    cwd=str(SCRIPT_DIR),
                    instance_id=instance_id,
                )
            else:
                logger.warning("Cycle produced no result")

            _read_sleep_signal(config, instance_id)

            cleanup_between_cycles(SCRIPT_DIR)
    finally:
        lock.release()
